spring:
  application:
    name: smart-bin-tracker
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  web:
    resources:
      static-locations: classpath:/static/
  
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME:}
          account-key: ${AZURE_STORAGE_ACCOUNT_KEY:}
          endpoint: ${AZURE_STORAGE_ENDPOINT:}
          container-name: ${AZURE_STORAGE_CONTAINER:smartbin-files}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.smartbin: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:smartBinSecretKeyForJWTTokenGeneration2024}
    expiration: 86400000 # 24 hours
  
  admin:
    default-username: ${ADMIN_USERNAME:admin}
    default-password: ${ADMIN_PASSWORD:admin123}
  
  storage:
    upload-dir: ${UPLOAD_DIR:uploads}
    max-file-size: 10MB
    max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: azure
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: false

logging:
  level:
    com.smartbin: INFO
    root: INFO 